--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BajanVlogs/YTApplication
build-by-default: true
branches:
- main
projects:
  YTApplication:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
...
